spring.application.name=hospital_system
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://root:KlPvohVbwHCzWKiDOMdIOQqyEqpzTMhT@turntable.proxy.rlwy.net:25997/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:KlPvohVbwHCzWKiDOMdIOQqyEqpzTMhT}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect